fixtures:
  repositories:
    concat:  "https://github.com/puppetlabs/puppetlabs-concat"
    openbsd: "https://github.com/duritong/puppet-openbsd"
    stdlib:  "https://github.com/puppetlabs/puppetlabs-stdlib"

  symlinks:
    munin: "#{source_dir}"
