#!/bin/sh
# -*- sh -*-
#
# Plugin to count the daily amount of Virii (qmailscan)
#
# Contributed by David Obando (david@cryptix.de) - 03.12.2005
#

# define the logfiles. when you rotate them at any other time than 00:00 you have to define two logfiles:
#LOG0=/var/spool/qmailscan/quarantine.log
#LOG1=/var/spool/qmailscan/quarantine.log.1

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title enforced amount'
        echo 'graph_args --upper-limit 1 -l 0 '
        echo 'graph_vlabel Is the system selinux enforced?'
        echo 'graph_scale no\n';
        echo 'graph_category selinux'
                echo 'enforced.label IsEnforced'
        #echo 'enforced.draw AREA'
                echo 'enforced.draw LINE2'

        exit 0
fi

echo -n "enforced.value " && cat /selinux/enforce

